export const FETCHING_USER_REQUEST = 'FETCHING_USER_REQUEST';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const Clear_USER_REQUEST = 'Clear_USER_REQUEST';
export const PRODUCT_SELECTED = 'PRODUCT_SELECTED';
